Sukru
omeryttnc/KesifPlus_2024 pull request #2
Opened 2024-02-02 15:05 UTC by Schukru

2024-02-08 19:47 UTC, omeryttnc commented on FridayProjects/src/test/java/utilities/JSUtils.java
> +    public static void generateAlert(String message) throws InterruptedException {
burdaki exception atamayi kaldirabilir misiniz

2024-02-08 19:50 UTC, omeryttnc requested changes
Sukru bey iki yerde exception atamissiniz onlari kaldirabilir misiniz

2024-02-08 22:35 UTC, Schukru commented on FridayProjects/src/test/java/utilities/ReusableMethods.java
> +    public static String getScreenshot() throws IOException {
exception ataması try/catch ile düzeltildi

2024-02-08 22:36 UTC, Schukru commented on FridayProjects/src/test/java/utilities/ReusableMethods.java
> +        //FluentWait<WebDriver> wait = new FluentWait<WebDriver>(Driver.getDriver()).withTimeout(timeinsec, TimeUnit.SECONDS).pollingEvery(timeinsec, TimeUnit.SECONDS);
tüm yoruma alınmış satırlar kaldırıldı

2024-02-09 00:35 UTC, omeryttnc approved these changes

2024-02-09 00:35 UTC, merged